### ISSUE TITLE
Criação de formulario para solicitar CNPJ e retornar dados a partir da api https://brasilapi.com.br/

### ISSUE THREAD

**Issue by mobilecosta** [mobilecosta/protheus#1]
Consumo em
https://brasilapi.com.br/api/cnpj/v1/10480616000160

**Comment by guilhermeforprojeto** [comment]
Em conversação com Wagner foi indicado utilizar o po-dynamic-form para o CRUD  segue o link https://po-ui.io/documentation/po-dynamic-form

**Comment by mobilecosta** [comment]
Tarefa executada.
