### ISSUE TITLE
nuv001-Criação de crud para manutenção do metodo Empresa

### ISSUE THREAD

**Issue by mobilecosta** [mobilecosta/protheus#3]
1) Inclusão de menu da opção
2) Criação de Grid, e crud (incluir, alterar e excluir), conforme documentação em https://api.sandbox.nuvemfiscal.com.br/swaggerui#/Empresa

____________

NOTAS: 
Token 

Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODU0NTIzMzMsInRlbmFudF9pZCI6IldhZ25lciBNb2JpbGUgQ29zdGEjOTY2OCJ9.zBC9QpfHhDJmFWI9yUxeQNv819piFqN8v6utLOSJphI

Apontamentos: https://docs.google.com/spreadsheets/d/11tf9KX0M0pfRDq6KtNf84pDx2oUDb1pLBtZvdab66fw/edit#gid=399437436

**Comment by guilhermeforprojeto** [comment]
Alterei o botao teste para empresas e copiei o componente CPNJ para o mesmo

**Comment by guilhermeforprojeto** [comment]
Peguei o componente CPNJ e alterei os imports e nomes de arquivos para companies....

**Comment by guilhermeforprojeto** [comment]
Encontrei o componente usuario quem tem o grid que precisamos entao estou fazaendo de novo o processo porem usando agora o componente grid"user" como base

**Comment by guilhermeforprojeto** [comment]
Coloquei o GRID dentro de companies

**Comment by guilhermeforprojeto** [comment]
Em conversação com Wagner foi indicado utilizar o po-dynamic-form para o CRUD  segue o link https://po-ui.io/documentation/po-dynamic-form

**Comment by guilhermeforprojeto** [comment]
Alterei o icone do menu empresas, mudei o end-point, ainda estou procurando como resolver a renderização do componente empresas na aplicação sem mudar a pagina manda a side-bar.

**Comment by guilhermeforprojeto** [comment]
Arrumei a renderizaçao de componente Empresas que antes mudar de pagina e agora renderiza na mesma pagina como esperado.

**Comment by guilhermeforprojeto** [comment]
Resolvi alguns erros de importação no componente companies

**Comment by guilhermeforprojeto** [comment]
Primeiro get com sucesso no grid de empresas

**Comment by guilhermeforprojeto** [comment]
Campos para aparecer na tela iniciar do componente empresas. 

"endereco": {
        "logradouro": "string",
        "numero": "string",
        "complemento": "string",
        "bairro": "string",
        "codigo_municipio": "string",
        "cidade": "string",
        "uf": "string",
        "codigo_pais": "string",
        "pais": "string",
        "cep": "string"
      },

**Comment by guilhermeforprojeto** [comment]
No momento temos apenas o GET para empresas mas não para uma empresa especifica por exemploi  api/empresas/{cpf_cnpj}

**Comment by guilhermeforprojeto** [comment]
CRUD esta funcional, estou nos ajustes finos para melhor uso do usuario
